{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.geniee.gnadgooglemediationadapter",
    "module": "GNAdGoogleMediationAdapter",
    "version": "25.2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GNAdGoogleMediationAdapter-25.2.0.1.aar",
          "url": "GNAdGoogleMediationAdapter-25.2.0.1.aar",
          "size": 7297,
          "sha512": "990f6083b9cbaae2cae9b173dabf9b0d2280b84ace0b5205e9fd437ce32b25cdf8a87f3f009ec4eec836b984543b428a80201bfba579c68deeb529474f2ea6ec",
          "sha256": "939e877adcfe4e00ac662375943ec2c0fdda913c3a7150e0d7fa622fc0fe83f4",
          "sha1": "a832ab5e3cced29538bfd6d94f14cfc9641e5af1",
          "md5": "8ad14851e0455ac7d8988835480d81de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "GNAdGoogleMediationAdapter-25.2.0.1.aar",
          "url": "GNAdGoogleMediationAdapter-25.2.0.1.aar",
          "size": 7297,
          "sha512": "990f6083b9cbaae2cae9b173dabf9b0d2280b84ace0b5205e9fd437ce32b25cdf8a87f3f009ec4eec836b984543b428a80201bfba579c68deeb529474f2ea6ec",
          "sha256": "939e877adcfe4e00ac662375943ec2c0fdda913c3a7150e0d7fa622fc0fe83f4",
          "sha1": "a832ab5e3cced29538bfd6d94f14cfc9641e5af1",
          "md5": "8ad14851e0455ac7d8988835480d81de"
        }
      ]
    }
  ]
}
