[versions]
agp = "8.5.2"
kotlin = "1.9.24"
google-services = "4.4.2"

googleads = "25.2.0"
gnadsdk = "8.7.5"

# AndroidX
appcompat = "1.1.0"
constraintlayout = "1.1.3"
recyclerview = "1.3.2"
cardview = "1.0.0"
multidex = "2.0.1"
annotation = "1.1.0"
core-ktx = "1.12.0"

# Firebase
firebase-bom = "30.1.0"

[libraries]
google-play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "googleads" }
gnadsdk = { group = "jp.co.geniee.gnadsdk", name = "GNAdSDK", version.ref = "gnadsdk" }

# AndroidX
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-ads = { group = "com.google.firebase", name = "firebase-ads" }
firebase-core = { group = "com.google.firebase", name = "firebase-core" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
