{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.geniee.mediation",
    "module": "google-ad-manager",
    "version": "25.2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "google-ad-manager-25.2.0.0.aar",
          "url": "google-ad-manager-25.2.0.0.aar",
          "size": 12035,
          "sha512": "df1b5d07eb2f630cde4987c9c3100b709b9876b9ee21e9da0c1f8e8425643c01bdff8f83e084d3dd795e605054fff2b4f85497de933d3db09702530f19c3d9f3",
          "sha256": "510c74cf7e15374b3ff34de97e81b3de81ab1d08a365a788e12fa59f27ac382b",
          "sha1": "5ee812ffce4b99c68f66e8379f037ec6e7cd050c",
          "md5": "229fc581f6b82f0a393bd4861eddb15c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "google-ad-manager-25.2.0.0.aar",
          "url": "google-ad-manager-25.2.0.0.aar",
          "size": 12035,
          "sha512": "df1b5d07eb2f630cde4987c9c3100b709b9876b9ee21e9da0c1f8e8425643c01bdff8f83e084d3dd795e605054fff2b4f85497de933d3db09702530f19c3d9f3",
          "sha256": "510c74cf7e15374b3ff34de97e81b3de81ab1d08a365a788e12fa59f27ac382b",
          "sha1": "5ee812ffce4b99c68f66e8379f037ec6e7cd050c",
          "md5": "229fc581f6b82f0a393bd4861eddb15c"
        }
      ]
    }
  ]
}
