{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.geniee.mediation",
    "module": "unityads",
    "version": "4.18.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "unityads-4.18.0.0.aar",
          "url": "unityads-4.18.0.0.aar",
          "size": 12981,
          "sha512": "de404ac44155cfb5fd729dc1f22e420b386575bebc7f6b935a61ed8d0cdfc4238441026e3f5d8429302771a200772ef4aac840b5b9a522e17f9fd98410b53f16",
          "sha256": "f7ccca48fd4a0789723dc51092a310f80d34ac9b4a2f856f0558b4346117d4d4",
          "sha1": "999d6f07d8d8c944acd0164fb5a26a4b2c5fefce",
          "md5": "187ec0125537a6e1bb63ae376ccac867"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "unityads-4.18.0.0.aar",
          "url": "unityads-4.18.0.0.aar",
          "size": 12981,
          "sha512": "de404ac44155cfb5fd729dc1f22e420b386575bebc7f6b935a61ed8d0cdfc4238441026e3f5d8429302771a200772ef4aac840b5b9a522e17f9fd98410b53f16",
          "sha256": "f7ccca48fd4a0789723dc51092a310f80d34ac9b4a2f856f0558b4346117d4d4",
          "sha1": "999d6f07d8d8c944acd0164fb5a26a4b2c5fefce",
          "md5": "187ec0125537a6e1bb63ae376ccac867"
        }
      ]
    }
  ]
}
