{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.geniee.mediation",
    "module": "pangle",
    "version": "8.0.0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pangle-8.0.0.4.0.aar",
          "url": "pangle-8.0.0.4.0.aar",
          "size": 16057,
          "sha512": "9438e84bc03e87d4d61a93578d07ddd8e0244f80b745f253ea1dbc3366e29543050d74347340eb21495c743c5228ad0645ce5857ea58fece9020a7d2db5aba60",
          "sha256": "35346be16072b1f728781a540c5605becf548087632516da7d221fe5aeb7907c",
          "sha1": "906d08b84c63e704d2fb561c58d8050ba9e0b9af",
          "md5": "9fbedc88ec8d10c6462f46358eb5cb36"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pangle.global",
          "module": "pag-sdk",
          "version": {
            "requires": "8.0.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "pangle-8.0.0.4.0.aar",
          "url": "pangle-8.0.0.4.0.aar",
          "size": 16057,
          "sha512": "9438e84bc03e87d4d61a93578d07ddd8e0244f80b745f253ea1dbc3366e29543050d74347340eb21495c743c5228ad0645ce5857ea58fece9020a7d2db5aba60",
          "sha256": "35346be16072b1f728781a540c5605becf548087632516da7d221fe5aeb7907c",
          "sha1": "906d08b84c63e704d2fb561c58d8050ba9e0b9af",
          "md5": "9fbedc88ec8d10c6462f46358eb5cb36"
        }
      ]
    }
  ]
}
