plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'jp.co.geniee.samples'
    compileSdk 35

    defaultConfig {
        applicationId "jp.co.geniee.samples"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        disable "ResourceType"
        abortOnError false
    }
}

dependencies {
    implementation libs.google.play.services.ads
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.recyclerview
    implementation libs.cardview
    implementation libs.multidex
    implementation libs.annotation
    implementation libs.gnadsdk

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
